### ISSUE TITLE
Stats.txt

### ISSUE THREAD

**Issue by MamtaBhagia** [NVlabs/geomapnet#1]
Downloading the 7Scenes dataset doesn't come with a stats.txt and pose_stats.txt file. How is that file formed?

**Comment by jwgu** [comment]
These are statistics (i.e., mean and std) of the dataset, computed with scripts/dataset_mean.py. See the README.md for details. For 7Scenes and RobotCar, these statistics are already pre-computed and put in the corresponding folders.
