### ISSUE TITLE
How to create a VO file for Robotcar?

### ISSUE THREAD

**Issue by wangq95** [NVlabs/geomapnet#11]
Hi, I have a question about how to create a file for Robotcar dataset to do VO, such as ORB-SLAM2, there is only process code for  KITTI and 7Scene datasets i dir scripts, how to get the rotation matrix and transpose vector to employ the VO? Thank you!

**Comment by samarth-robo** [comment]
The RobotCar dataset supplies the VO file, see https://github.com/NVlabs/geomapnet/issues/5#issuecomment-416657899.
