### ISSUE TITLE
Error occur while creating Network Attention Visualization

### ISSUE THREAD

**Issue by DRAhmadFaraz** [NVlabs/geomapnet#12]
@samarth-robo 

I have to run the function "Network Attention Visualization" by that command as an input 

"python plot_activations.py --dataset 7Scenes --scene heads --weights logs/7Scenes_heads_mapnet++_mapnet++_7Scenes/epoch_005.pth.tar --device 1 --config_file configs/mapnet++_7Scenes.ini --output_dir ../results/"

and get an error of

Loaded weights from logs/7Scenes_heads_mapnet++_mapnet++_7Scenes/epoch_005.pth.tar
Visualizing TRAIN data
Traceback (most recent call last):
  File "plot_activations.py", line 83, in <module>
    data_set = SevenScenes(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'sequence'

![Screenshot from 2019-03-11 20-28-07](https://user-images.githubusercontent.com/38114191/54155543-3e921b80-443c-11e9-8d35-82b4721bb3bc.png)

Please guide me how to run this Network Attention Visualization

**Comment by samarth-robo** [comment]
This is a case of wrong keyword argument to the dataset creation function. I pushed the fix - it should work now.
