### ISSUE TITLE
How to get the  DSO: Direct sparse odometry for our own dataset

### ISSUE THREAD

**Issue by DRAhmadFaraz** [NVlabs/geomapnet#17]
@samarth-robo, 
Respected Sir, I have successfully installed your code and it works fine on 7-Scenes dataset, 

Now I want to run your code on my own Images, I have extracted the `frame00xxx-pose.txt` for every corresponding images by using Visual-SFM, but here your code also needs the **DSO: Direct sparse odometry** of 12 values for the comparison, so can you please guide me how to extract the DSO from monocular images having 4x4 poses for each frame too..??

Or can you please guide me format of **DSO** file values, 

Is these values are also Rotation and Translation.?
and what is the format of these files in that text file named `"dso_poses/seq-xx.txt".??` like 12 values shows what.? which values are for which parameters for camera.?

waiting for your kind response,
Best regards.

**Comment by DRAhmadFaraz** [comment]
@samarth-robo

**Comment by DRAhmadFaraz** [comment]
@samarth-robo Waiting for your response.

**Comment by DRAhmadFaraz** [comment]
@samarth-robo Sir, please guide me

**Comment by DRAhmadFaraz** [comment]
@samarth-robo

**Comment by DRAhmadFaraz** [comment]
@samarth-robo

**Comment by DRAhmadFaraz** [comment]
@samarth-robo

**Comment by samarth-robo** [comment]
Hi @DRAhmadFaraz , the 12 values in the `.txt` files are the flattened 3x4 pose matrix, used by the `process_poses()` function in [pose_utils.py](common/pose_utils.py).
VO algorithms typically output the relative camera pose between consecutive frames, you will have to compute the absolute pose trajectory by chaining together those relative poses.

**Comment by samarth-robo** [comment]
Closing this issue now, feel free to re-open if you have more questions.

**Comment by DRAhmadFaraz** [comment]
How to get such relative poses from Monocular images.?
