### ISSUE TITLE
How to load our own custom monocular RGB dataset.?

### ISSUE THREAD

**Issue by DRAhmadFaraz** [NVlabs/geomapnet#20]
How to load our own custom monocular RGB dataset.?

Can I use Visual-SFM for poses.?
and How to get `"DSO pose text file"`, ` "dso_vo_stats.pkl`", `"libviso2_vo_stats.pkl" `and` "orbslam_vo_stats.pkl"` files.?

**Comment by samarth-robo** [comment]
Hi, those xx_vo_stats.pkl files store the global rotation and translation that aligns the integrated VO trajectory with the ground truth trajectory. Please see `scripts/align_vo_poses.py` for examples.
