### ISSUE TITLE
Implementation on Python 3

### ISSUE THREAD

**Issue by yxgeee** [NVlabs/geomapnet#25]
Kindly ask that is there an implementation for python 3 environment?
I could not achieve the right results when directly transferring to python 3, maybe there are some small issues about the calculation process.
Thanks a lot.

**Comment by samarth-robo** [comment]
@yxgeee Sorry I don't plan to add python 3 support soon. PRs are welcome!
Note that the errors might also come from the robotcar dataset SDK. Some time ago I worked on a [python 3 version](https://github.com/samarth-robo/robotcar-dataset-sdk/tree/python3) of it, which might be useful.
Do you observe differences on the 7 scenes dataset or robotcar?

**Comment by mcimpoi** [comment]
I have one fork, for 3.6, https://github.com/mcimpoi/geomapnet  -- tested for posenet, 7scenes so far.
I didn't verify that the numbers are matching. I hope to prepare this as a PR at some point.

Please use the environment_py36.yml file to create the python 3.6  env.

**Comment by yxgeee** [comment]
> I have one fork, for 3.6, https://github.com/mcimpoi/geomapnet -- tested for posenet, 7scenes so far.
> I didn't verify that the numbers are matching. I hope to prepare this as a PR at some point.
> 
> Please use the environment_py36.yml file to create the python 3.6 env.

Thanks a lot!

**Comment by yxgeee** [comment]
@samarth-robo @mcimpoi Thanks a lot!
