### ISSUE TITLE
share the web link of Robotcar dataset you used in loop scene.

### ISSUE THREAD

**Issue by DRAhmadFaraz** [NVlabs/geomapnet#26]
@samarth-robo 

share the web link of Robotcar dataset you used in loop scene.

Regards

**Comment by samarth-robo** [comment]
The download page is https://robotcar-dataset.robots.ox.ac.uk/datasets/ for all the Robotcar datasets. You will need to make an account with them to be able to download.

For each day (e.g. `DAY=2014-05-14-13-46-12`) you should download `DAY_stereo_center.tar` and `DAY_vo.tar` from the Bumblebee XB3 section, and `DAY_gps.tar` from the GPS/INS section.

Each dataset in our paper is a collection of days. For example, the `loop` dataset is a collection of 6 days. You can find the list of days in `data/RobotCar/loop/`. Some of those days are used for training and some for testing. You can find the train/test split in `data/deepslam_data/RobotCar/loop`.
