### ISSUE TITLE
Error Calculate pose translation statistics

### ISSUE THREAD

**Issue by DRAhmadFaraz** [NVlabs/geomapnet#27]
@samarth-robo 

Error using `python calc_pose_stats.py --dataset 7Scenes --scene redkitchen` command

Traceback (most recent call last):
  File "calc_pose_stats.py", line 29, in <module>
    dset = SevenScenes(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'sequence'

![Screenshot from 2019-10-02 15-29-27](https://user-images.githubusercontent.com/38114191/66037658-92c03280-e529-11e9-8e50-3c28a009e670.png)

**Comment by samarth-robo** [comment]
Commit 11786ea should fix it.
