### ISSUE TITLE
complications on DSO implementation on 7 scenes dataset (heads)

### ISSUE THREAD

**Issue by DRAhmadFaraz** [NVlabs/geomapnet#28]
Respected @samarth-robo Sir,

With due Respect I just want to ask one basic question that How can I able to exlude relative poses by running [`DSO`](https://github.com/JakobEngel/dso) algorithem.

I used this **camera calibration files** in their algorithm as below.

`0.914 1.218 0.5 0.5 0`
`640 480`
`crop`
`640 480`

**which meant to be in that format**
Calibration File for Pre-Rectified Images
`Pinhole fx fy cx cy 0`
`in_width in_height`
`"crop" / "full" / "none" / "fx fy cx cy 0"`
`out_width out_height`

I gave `7scenes/heads/seq1` folder to dso as input which includes 0-999 color images.

The DSO algorithm gives me 290 camera poses in `results.txt `file in a format of ` ([timestamp x y z qx qy qz qw]` 

And I observed that you used same DSO algorithm and exclude 12-999 poses as shown in this 
[link](https://github.com/NVlabs/geomapnet/blob/master/data/7Scenes/heads/dso_poses/seq-01.txt)

I want this same exact as it is to run the mapnet++ for my own dataset but on 7 scenes or any dataset when I run that DSO, it gave me less poses info of few images instead of poses of every corresponding images.

I dont understand that for `7scenes/heads/seq-1 ` after passing **1000** images, I just get **290** poses, where are the remaining poses? and these 290 poses are of whose images.?

please help me to resolve it.

I will be thankful to you.

Best Regards

**Comment by samarth-robo** [comment]
Hi @DRAhmadFaraz , firstly, I think you will get more information by asking the DSO authors about this question. My guess is that DSO fails to optimize the poses for the excluded frames. That could be because of many reasons. As to which images those 290 poses are for, that is indicated in the `timestamp`. I'm not sure, but it could be that `timestamp` shows the indices of the frames.
