### ISSUE TITLE
Problems about plot_activation

### ISSUE THREAD

**Issue by drinkingcoder** [NVlabs/geomapnet#3]
Hi, there is a problem confuses me about attention map. You figure out attention by this:
```
pose = model(data_val)
pose.mean().backward()
```
It seems that you want to some unsupervised back propagation, but how does 'pose.mean()' work? Do you want to calculate the mean of the 7 dimension vector?

**Comment by samarth-robo** [comment]
The mean of the pose vector does not have a physical meaning.
To calculate attention, we want to see how much each pixel can change *any* element of the output pose vector. One way to do this is to look at the gradient of the mean of the output pose vector w.r.t. image pixel.
