### ISSUE TITLE
Problem with the result

### ISSUE THREAD

**Issue by jialuwang123321** [NVlabs/geomapnet#36]
Dear, 
  I ran the eval.py using the pre-trained weights of the loop dataset (named/RobotCar_loop_mapnet_mapnet_learn_beta_learn_gamma/epoch_300_.pth.tar'). 
  However, the result didn't match that from the paper (see figure below).  
![issue0910](https://user-images.githubusercontent.com/58662114/92711696-57f68980-f38b-11ea-91c5-d88ca00e1a62.JPG)

  May I have some suggestions for it?

Best!
Jialu

**Comment by samarth-robo** [comment]
Hi @jialuwang123321 , I've noticed sometimes the issue arises from PyTorch version. Have you 1) set up the Conda environment properly? 2) activated it? 3) what is your PyTorch version?

**Comment by jialuwang123321** [comment]
Dear&nbsp;Samarth Brahmbhatt,&nbsp;
&nbsp; Thank you so much for your help!
&nbsp; I changed from torch 1.4.0 to torch 0.4.1 and it is working now!


Best
Jialu




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Samarth Brahmbhatt"<notifications@github.com&gt;; 
发送时间: 2020年9月11日(星期五) 凌晨1:13
收件人: "NVlabs/geomapnet"<geomapnet@noreply.github.com&gt;; 
抄送: "Ashley "<maggirapple@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [NVlabs/geomapnet] Problem with the result (#36)





 
Hi @jialuwang123321 , I've noticed sometimes the issue arises from PyTorch version. Have you 1) set up the Conda environment properly? 2) activated it? 3) what is your PyTorch version?

**Comment by jialuwang123321** [comment]
Dear @samarth-robo , 
  Thank you so much for your help!
  I changed from torch 1.4.0 to torch 0.4.1 and it is working now!

Best
Jialu
