### ISSUE TITLE
 a question for the initializations about Beta in _mapnet.ini_

### ISSUE THREAD

**Issue by yuzewang1998** [NVlabs/geomapnet#42]
Hi Samarth,
I am implement your paper and I have a question for the initializations about Beta in _mapnet.ini_ .I found that you set Beta = -3.0 in _mapnet.ini_ ,and in your paper (Section 3.5. Implementation Details) you choose Beta = 0.0 instead.

![image](https://user-images.githubusercontent.com/34028809/126945611-463a2532-6e26-4532-81e3-279778b8026b.png)

Can I learn from you that which is the better initialization for Beta, and whether it has some reason to choose that  initialization?
Thanks, waiting for your reply.

**Comment by samarth-robo** [comment]
Hi @novasky0709! I think others have asked similar questions before. I have tried to compile hyper parameter information in [this README](https://github.com/NVlabs/geomapnet/blob/master/scripts/configs/README.md) based on those questions. Does it answer your question?

**Comment by yuzewang1998** [comment]
Hi @samarth-robo ! Thanks for your reply .In that README ,beta was only explained the meaning (absolute pose) but wasn't given a value . So I think the initialization for Beta is the same as the paper . In paper , beta was initialized by 0.0 . In mapnet.ini, beta was initialized by -3.0. So I wonder if there's some reasons for that initialization.

**Comment by samarth-robo** [comment]
@novasky0709 that README I linked has this line: "beta is the initial value of Gamma (Eq. 3 of the paper) for absolute pose".

**Comment by yuzewang1998** [comment]
Thanks for your reply.
