### ISSUE TITLE
basic question

### ISSUE THREAD

**Issue by AndreV84** [NVlabs/geomapnet#5]
any ideas how to overcome the below?
Loaded weights from logs/7Scenes_heads_mapnet++_mapnet++_7Scenes/epoch_005.pth.tar
Running mapnet++ on VAL data
Traceback (most recent call last):
File "eval.py", line 124, in 
vo_func=vo_func, no_duplicates=False, **kwargs)
File "../dataset_loaders/composite.py", line 45, in init
self.dset = SevenScenes(*args, real=self.real, **kwargs)
File "../dataset_loaders/seven_scenes.py", line 52, in init
with open(split_file, 'r') as f:
IOError: [Errno 2] No such file or directory: '../data/deepslam_data/7Scenes/heads/TestSplit.txt'

**Comment by samarth-robo** [comment]
It is missing the file `../data/deepslam_data/7Scenes/heads/TestSplit.txt`. Did you download the 7 Scenes dataset and put it in the correct location as mentioned [here](https://github.com/NVlabs/geomapnet#data)?

**Comment by AndreV84** [comment]
what exactly mentioning are you referring to?
First I downloaded datasets with 
`"Microsoft 7 Scenes:

onepanel download onepanel-demo/datasets/rgb-d-7scenes 7SCENES_DIR

NVIDIA pre-trained geomap models:

onepanel download onepanel-demo/datasets/nvidia-geomap-models logs

Sample Video Data from Robot
pip install awscli

aws s3 sync s3://onepanel-digilabs-datasets rover_data"`
then I downloaded the folder https://drive.google.com/drive/folders/1J2QG_nHrRTKcDf9CGXRK9MWH1h-GuMLy
Could you expand how do I get the 7Scenes dataset in a way it will come with the TestSplit.txt file, please? Because even at the source [https://github.com/NVlabs/geomapnet/tree/master/data/7Scenes/heads] I can not see the TestSplit.txt file

**Comment by AndreV84** [comment]
hm, I foound Text.Split for robotcar https://github.com/NVlabs/geomapnet/tree/master/data/deepslam_data/RobotCar/full , but where do I get the missed file for 7Scenes?

**Comment by AndreV84** [comment]
shall I get them from http://download.microsoft.com/download/2/8/5/28564B23-0828-408F-8631-23B1EFF1DAC8/heads.zip ?

**Comment by AndreV84** [comment]
got it regarding the issue above,
but it got throwing another[previously resolved already by putting the models to scripts/logs folder] issue that now emerged again by unknown reason.
mapnet_release) /onepanel/code/scripts (master) $ cd ..
(mapnet_release) /onepanel/code (master) $ ls
1            README.md       common           digilabs         logs                           logs-20180729T074545Z-003.zip  logs-20180729T074545Z-006.zip  rover_data
7SCENES_DIR  Untitled.ipynb  data             environment.yml  logs-20180729T074545Z-001.zip  logs-20180729T074545Z-004.zip  logs-20180729T074545Z-007.zip  scripts
LICENSE.md   combined        dataset_loaders  figures          logs-20180729T074545Z-002.zip  logs-20180729T074545Z-005.zip  models                         unzip
(mapnet_release) /onepanel/code (master) $ cd data
(mapnet_release) /onepanel/code/data (master) $ ls
7Scenes  README.txt  RobotCar  deepslam_data  robotcar-dataset-sdk  robotcar_camera_models
(mapnet_release) /onepanel/code/data (master) $ ls
7Scenes  README.txt  RobotCar  deepslam_data  robotcar-dataset-sdk  robotcar_camera_models
(mapnet_release) /onepanel/code/data (master) $ mv ../rover_data/ rover_data
(mapnet_release) /onepanel/code/data (master) $ conda deactivate mapnet-release
deactivate does not accept arguments
remainder_args: ('mapnet-release',)

(mapnet_release) /onepanel/code/data (master) $ conda deactivate
(base) /onepanel/code/data (master) $ cd ..
(base) /onepanel/code (master) $ cd scripts/
(base) /onepanel/code/scripts (master) $ python eval.py --dataset 7Scenes --scene heads --model mapnet++ --weights logs/7Scenes_heads_mapnet++_mapnet++_7Scenes/epoch_005.pth.tar 
  File "eval.py", line 89
    print 'Loaded weights from {:s}'.format(weights_filename)
                                   ^
SyntaxError: invalid syntax
(base) /onepanel/code/scripts (master) $ ls
__init__.py                calc_pose_stats.py          dataset_mean.py          logs                       plot_vo_poses.py         process_robotcar_images.py  set_paths.pyc
align_vo_poses.py          calc_pose_stats_7scenes.sh  dataset_mean_7Scenes.sh  make_robotcar_symlinks.sh  process_7_scenes.sh      reverse_vo_poses.py         test_vo.py
align_vo_poses_7scenes.sh  configs                     eval.py                  plot_activations.py        process_robotcar_gps.py  set_paths.py                train.py
(base) /onepanel/code/scripts (master) $ ls -l logs/
total 552
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:04 7Scenes_chess_mapnet++_mapnet++_7Scenes
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:02 7Scenes_chess_mapnet_mapnet_learn_beta_learn_gamma
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:04 7Scenes_chess_posenet_posenet_learn_beta_logq
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:02 7Scenes_chess_posenet_posenet_learn_beta_quat
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:04 7Scenes_fire_mapnet++_mapnet++_7Scenes
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:04 7Scenes_fire_mapnet_mapnet_learn_beta_learn_gamma
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:04 7Scenes_fire_posenet_posenet_learn_beta_logq
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:04 7Scenes_fire_posenet_posenet_learn_beta_quat
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:04 7Scenes_heads_mapnet++_mapnet++_7Scenes
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:04 7Scenes_heads_mapnet_mapnet_learn_beta_learn_gamma
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:03 7Scenes_heads_posenet_posenet_learn_beta_logq
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:02 7Scenes_heads_posenet_posenet_learn_beta_quat
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:04 7Scenes_office_mapnet++_mapnet++_7Scenes
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:04 7Scenes_office_mapnet_mapnet_learn_beta_learn_gamma
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:03 7Scenes_office_posenet_posenet_learn_beta_logq
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:03 7Scenes_office_posenet_posenet_learn_beta_quat
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:02 7Scenes_pumpkin_mapnet++_mapnet++_7Scenes
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:04 7Scenes_pumpkin_mapnet_mapnet_learn_beta_learn_gamma
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:02 7Scenes_pumpkin_posenet_posenet_learn_beta_logq
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:03 7Scenes_pumpkin_posenet_posenet_learn_beta_quat
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:04 7Scenes_redkitchen_mapnet++_mapnet++_7Scenes
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:04 7Scenes_redkitchen_mapnet_mapnet_learn_beta_learn_gamma
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:02 7Scenes_redkitchen_posenet_posenet_learn_beta_logq
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:03 7Scenes_redkitchen_posenet_posenet_learn_beta_quat
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:03 7Scenes_stairs_mapnet++_mapnet++_7Scenes
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:03 7Scenes_stairs_mapnet_mapnet_learn_beta_learn_gamma
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:02 7Scenes_stairs_mapnet_mapnet_learn_beta_learn_gamma_k_10_s_3
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:03 7Scenes_stairs_posenet_posenet_learn_beta_logq
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:03 7Scenes_stairs_posenet_posenet_learn_beta_quat
-rwxrwxrwx 1 onepanel users 383050 Jul 29 09:02 README.docx
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:03 RobotCar_full_mapnet++_mapnet++_RobotCar_learn_beta_learn_gamma
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:02 RobotCar_full_mapnet++_mapnet++_RobotCar_learn_beta_learn_gamma_gps
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:03 RobotCar_full_mapnet_mapnet_learn_beta_learn_gamma
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:02 RobotCar_full_posenet_posenet_learn_beta_logq
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:02 RobotCar_loop_1seq_mapnet++_mapnet++_RobotCar_learn_beta_learn_gamma_1seq
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:03 RobotCar_loop_1seq_mapnet++_mapnet++_RobotCar_learn_beta_learn_gamma_2seq
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:03 RobotCar_loop_1seq_mapnet++_mapnet++_RobotCar_learn_beta_learn_gamma_3seq
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:02 RobotCar_loop_1seq_mapnet_mapnet_learn_beta_learn_gamma
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:03 RobotCar_loop_3seq_mapnet_mapnet_learn_beta_learn_gamma
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:03 RobotCar_loop_4seq_mapnet_mapnet_learn_beta_learn_gamma
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:03 RobotCar_loop_mapnet++_mapnet++_RobotCar_learn_beta_learn_gamma_1seq
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:04 RobotCar_loop_mapnet++_mapnet++_RobotCar_learn_beta_learn_gamma_2seq
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:03 RobotCar_loop_mapnet++_mapnet++_RobotCar_learn_beta_learn_gamma_2seq_gps
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:03 RobotCar_loop_mapnet_mapnet_learn_beta_learn_gamma
drwxrwxrwx 2 onepanel users   4096 Jul 29 09:02 RobotCar_loop_posenet_posenet_learn_beta_logq
(base) /onepanel/code/scripts (master) $ python eval.py --dataset 7Scenes --scene heads --model mapnet++ --weights logs/7Scenes_heads_mapnet++_mapnet++_7Scenes/epoch_005.pth.tar --config_file configs/pgo_inference_7Scenes.ini --val --pose_graph
  File "eval.py", line 89
    print 'Loaded weights from {:s}'.format(weights_filename)
                                   ^
SyntaxError: invalid syntax

**Comment by samarth-robo** [comment]
```
print 'Loaded weights from {:s}'.format(weights_filename)
^
SyntaxError: invalid syntax
```
our code is meant to be run with Python 2.7. It seems like you are running on Python 3.

**Comment by AndreV84** [comment]
got it, but now it is throwing:
(mapnet_release) /onepanel/code/scripts (master) $ python eval.py --dataset 7Scenes --scene heads --model mapnet++ --weights logs/7Scenes_heads_mapnet++_mapnet++_7Scenes/epoch_005.pth.tar --config_file configs/pgo_inference_7Scenes.ini --val --pose_graph
../models/posenet.py:62: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  nn.init.kaiming_normal(m.weight.data)
../models/posenet.py:64: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(m.bias.data, 0)
Loaded weights from logs/7Scenes_heads_mapnet++_mapnet++_7Scenes/epoch_005.pth.tar
Running mapnet++ on VAL data
Traceback (most recent call last):
  File "eval.py", line 124, in <module>
    vo_func=vo_func, no_duplicates=False, **kwargs)
  File "../dataset_loaders/composite.py", line 48, in __init__
    **kwargs)
  File "../dataset_loaders/seven_scenes.py", line 111, in __init__
    align_s=vo_stats[seq]['s'])
  File "../common/pose_utils.py", line 341, in process_poses
    poses_out[:, 0:3] = poses_in[:, [3, 7, 11]]
IndexError: too many indices for array

**Comment by samarth-robo** [comment]
That usually happens when it can't find the pose ground truth files. Check [this](https://github.com/NVlabs/geomapnet/blob/master/dataset_loaders/seven_scenes.py#L84) line and make sure the 7 Scenes dataset it set up properly, so that it can read the .txt files.

**Comment by AndreV84** [comment]
does the following appear to contain the correct path?
`(mapnet_release) /onepanel/code/data/deepslam_data/7Scenes (master) $ ls
chess  crop_size.txt  fire  heads  heads.zip  office  pumpkin  redkitchen  stairs  tsdf
(mapnet_release) /onepanel/code/data/deepslam_data/7Scenes (master) $ cd heads
(mapnet_release) /onepanel/code/data/deepslam_data/7Scenes/heads (master) $ ls
TestSplit.txt  TrainSplit.txt  dso_poses  heads.png  orbslam_poses  pose_stats.txt  seq-01  seq-01.zip  seq-02  seq-02.zip  stats.txt
(mapnet_release) /onepanel/code/data/deepslam_data/7Scenes/heads (master) $ cd ../../../
(mapnet_release) /onepanel/code/data (master) $ cd ..
(mapnet_release) /onepanel/code (master) $ cd dataset_loaders/
(mapnet_release) /onepanel/code/dataset_loaders (master) $ cat seven_scenes.py | grep pose.txt
          pss = [np.loadtxt(osp.join(seq_dir, 'frame-{:06d}.pose.txt'.`

**Comment by AndreV84** [comment]
shall I rename pose_stats.txt to pose.txt?

**Comment by AndreV84** [comment]
How do I 7 Scenes dataset it set up properly ?
if it resides in a form 
`/onepanel/code/data/deepslam_data/7Scenes/heads` with content 
`ls
TestSplit.txt   dso_poses  orbslam_poses   seq-01      seq-02      stats.txt
TrainSplit.txt  heads.png  pose_stats.txt  seq-01.zip  seq-02.zip`
does that appears proper?
could you provide the steps to configure the dataset in case reiterating the steps from a blank page[fresh install]?

**Comment by AndreV84** [comment]
(mapnet_release) /onepanel/code/scripts (master) $ python eval.py  --dataset 7Scenes --scene heads --model mapnet++ --weights logs/7Scenes_heads_mapnet++_mapnet++_7Scenes/epoch_005.pth.tar --config_file configs/pgo_inference_7Scenes.ini
../models/posenet.py:62: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  nn.init.kaiming_normal(m.weight.data)
../models/posenet.py:64: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(m.bias.data, 0)
Loaded weights from logs/7Scenes_heads_mapnet++_mapnet++_7Scenes/epoch_005.pth.tar
Running mapnet++ on TRAIN data
Could not load image ../data/deepslam_data/7Scenes/heads/seq-02/frame-000011.color.png, IOError: [Errno 2] No such file or directory: '../data/deepslam_data/7Scenes/heads/seq-02/frame-000011.color.png'
Could not load image ../data/deepslam_data/7Scenes/heads/seq-02/frame-000012.color.png, IOError: [Errno 2] No such file or directory: '../data/deepslam_data/7Scenes/heads/seq-02/frame-000012.color.png

**Comment by AndreV84** [comment]
does it look for the file "seq-01.txt" at line 84 of the file
`          pss = [np.loadtxt(osp.join(seq_dir, 'frame-{:06d}.pose.txt'.`
?

**Comment by AndreV84** [comment]
do I need the component below to the dataset files?
https://github.com/andyzeng/tsdf-fusion/tree/master/data/rgbd-frames

**Comment by AndreV84** [comment]
now  it outputs:
` python eval.py --dataset 7Scenes --scene heads --model mapnet++ --weights logs/7Scenes_heads_mapnet++_mapnet++_7Scenes/epoch_005.pth.tar --config_file configs/pgo_inference_7Scenes.ini --val --pose_graph
../models/posenet.py:62: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  nn.init.kaiming_normal(m.weight.data)
../models/posenet.py:64: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(m.bias.data, 0)
Loaded weights from logs/7Scenes_heads_mapnet++_mapnet++_7Scenes/epoch_005.pth.tar
Running mapnet++ on VAL data
Image 0 / 988
../common/train.py:339: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  data_var = Variable(data, volatile=(not train), requires_grad=train)
Image 200 / 988
Image 400 / 988
Image 600 / 988
Image 800 / 988
Error in translation: median 0.12 m,  mean 0.13 m
Error in rotation: median 8.46 degrees, mean 9.15 degree`

**Comment by samarth-robo** [comment]
OK, those numbers look good, seems like the issue is solved! I should probably update the README with the recommended PyTorch version number.

**Comment by AndreV84** [comment]
python eval.py --dataset RobotCar --scene loop --model mapnet++ --weights logs/RobotCar_loop_mapnet++_mapnet++_RobotCar_learn_beta_learn_gamma_2seq/epoch_005.pth.tar --config_file configs/pgo_inference_RobotCar.ini --val --pose_graph
../models/posenet.py:62: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  nn.init.kaiming_normal(m.weight.data)
../models/posenet.py:64: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(m.bias.data, 0)
Loaded weights from logs/RobotCar_loop_mapnet++_mapnet++_RobotCar_learn_beta_learn_gamma_2seq/epoch_005.pth.tar
Running mapnet++ on VAL data
Traceback (most recent call last):
  File "eval.py", line 124, in <module>
    vo_func=vo_func, no_duplicates=False, **kwargs)
  File "../dataset_loaders/composite.py", line 51, in __init__
    self.dset = RobotCar(*args, real=self.real, **kwargs)
  File "../dataset_loaders/robotcar.py", line 50, in __init__
    with open(split_filename, 'r') as f:
IOError: [Errno 2] No such file or directory: '../data/deepslam_data/RobotCar/loop/test_split.txt'
where to download the file from? do I get it from http://robotcar-dataset.robots.ox.ac.uk/ ?
the text.split has been located at the current github repository, thank you.
Now it needs another file though:
python eval.py --dataset RobotCar --scene loop --model mapnet++ --weights logs/RobotCar_loop_mapnet++_mapnet++_RobotCar_learn_beta_learn_gamma_2seq/epoch_005.pth.tar --config_file configs/pgo_inference_RobotCar.ini --val --pose_graph ../models/posenet.py:62: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_. nn.init.kaiming_normal(m.weight.data) ../models/posenet.py:64: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_. nn.init.constant(m.bias.data, 0) Loaded weights from logs/RobotCar_loop_mapnet++_mapnet++_RobotCar_learn_beta_learn_gamma_2seq/epoch_005.pth.tar Running mapnet++ on VAL data Traceback (most recent call last): File "eval.py", line 124, in <module> vo_func=vo_func, no_duplicates=False, **kwargs) File "../dataset_loaders/composite.py", line 51, in __init__ self.dset = RobotCar(*args, real=self.real, **kwargs) File "../dataset_loaders/robotcar.py", line 63, in __init__ with open(ts_filename, 'r') as f: IOError: [Errno 2] No such file or directory: '../data/deepslam_data/RobotCar/loop/2014-06-23-15-41-25/stereo.timestamps'
I get the 1gb sample from oxford robotics, do I put it all just to /data/deepslam/RobotCar/ or I need to sort it out to different folders?
I copied the file manually to the error path but now it errors with vo.csv not presented.
Where to get normal structure of the folder 2014-06-23-15-41-25 ?
cp stereo.timestamps /onepanel/code/data/deepslam_data/RobotCar/loop/2014-06-23-15-41-25/ (mapnet_release) /onepanel/code/data/deepslam_data/RobotCar/sample (master) $ cd ../ (mapnet_release) /onepanel/code/data/deepslam_data/RobotCar (master) $ cd ../../ (mapnet_release) /onepanel/code/data (master) $ cd ../scripts/ (mapnet_release) /onepanel/code/scripts (master) $ python eval.py --dataset RobotCar --scene loop --model mapnet++ --weights logs/RobotCar_loop_mapnet++_mapnet++_RobotCar_learn_beta_learn_gamma_2seq/epoch_005.pth.tar --config_file configs/pgo_inference_RobotCar.ini --val --pose_graph ../models/posenet.py:62: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_. nn.init.kaiming_normal(m.weight.data) ../models/posenet.py:64: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_. nn.init.constant(m.bias.data, 0) Loaded weights from logs/RobotCar_loop_mapnet++_mapnet++_RobotCar_learn_beta_learn_gamma_2seq/epoch_005.pth.tar Running mapnet++ on VAL data Traceback (most recent call last): File "eval.py", line 124, in <module> vo_func=vo_func, no_duplicates=False, **kwargs) File "../dataset_loaders/composite.py", line 51, in __init__ self.dset = RobotCar(*args, real=self.real, **kwargs) File "../dataset_loaders/robotcar.py", line 69, in __init__ p = np.asarray(interpolate_vo_poses(vo_filename, ts[seq], ts[seq][0])) File "../dataset_loaders/robotcar_sdk/interpolate_poses.py", line 34, in interpolate_vo_poses with open(vo_path) as vo_file: IOError: [Errno 2] No such file or directory: '../data/deepslam_data/RobotCar/loop/2014-06-23-15-41-25/vo/vo.csv' (mapnet_release) /onepanel/code/scripts (master) $ cd ..

**Comment by AndreV84** [comment]
but where to get the vo.csv for the RobotCar?

**Comment by samarth-robo** [comment]
From the Oxford Robotcar dataset, under the `Bumblebee XB3` section.

**Comment by AndreV84** [comment]
ty, but now it needs gps.csv
" No such file or directory: '../data/deepslam_data/RobotCar/loop/2014-06-23-15-41-25/gps/ins.csv"

**Comment by AndreV84** [comment]
i got the gps data, but now it appears to be datasets content mismatch:
but now it says on me executing :
python eval.py --dataset RobotCar --scene loop --model mapnet++ --weights logs/RobotCar_loop_mapnet++_mapnet++_RobotCar_learn_beta_learn_gamma_2seq/epoch_005.pth.tar --config_file configs/pgo_inference_RobotCar.ini --val --pose_graph
Could not load image ../data/deepslam_data/RobotCar/loop/2014-06-23-15-41-25/stereo/centre/1418381800826390.png, IOError: [Errno 2] No such file or directory: '../data/deepslam_data/RobotCar/loop/2014-06-23-15-41-25/stereo/centre/1418381800826390.png' Could not load image ../data/deepslam_data/RobotCar/loop/2014-06-23-15-41-25/stereo/centre/1418381800888890.png, IOError: [Errno 2] No such file or directory: '../data/deepslam_data/RobotCar/loop/2014-06-23-15-41-25/stereo/centre/1418381800888890.png'
the dataset I downloaded was http://mrgdatashare.robots.ox.ac.uk/download/?filename=datasets/2014-06-23-15-41-25/2014-06-23-15-41-25_stereo_centre_01.tar
and I just unpacked it to the loop folder of RobotCar folder.
Shall I download some other dataset?
currently the downloaded has different images numbers:
1403538187037944.png 1403538222975848.png 1403538259038757.png 1403538301914238.png 1403538338477142.png
1403538187100446.png 1403538223038352.png 1403538259101255.png 1403538301976739.png 1403538338539642.png

**Comment by AndreV84** [comment]
got it, it was stereo timestamps file, thx

**Comment by AndreV84** [comment]
![ma2vsfn](https://user-images.githubusercontent.com/16374873/44766660-07b48200-ab4a-11e8-8a34-54761a08bd5e.jpg)
seems executing
