### ISSUE TITLE
How to create a dso file for your own dataset

### ISSUE THREAD

**Issue by YibooWang** [NVlabs/geomapnet#50]
"Dear, I am sorry to disturb you. I have a question to consult. How to create the dso file of my own dataset, which is the txt file in the dso_poses folder? If you can share the code, I would be very grateful. I read your MapNet article and found it very interesting and meaningful, so I want to try my own dataset. Thank you very much."

**Comment by samarth-robo** [comment]
Hi @YibooWang thanks for your interest! I generated it by running the [DSO code](https://github.com/JakobEngel/dso) on the dataset, but I am afraid I cannot provide the exact code currently. There were no major modifications.
