### ISSUE TITLE
next question

### ISSUE THREAD

**Issue by AndreV84** [NVlabs/geomapnet#6]
```
python eval.py --dataset RobotCar --scene loop --model mapnet++ --weights logs/RobotCar_loop_mapnet++_mapnet++_RobotCar_learn_beta_learn_gamma_2seq/epoch_005.pth.tar --config_file configs/pgo_inference_RobotCar.ini --val --pose_graph
../models/posenet.py:62: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  nn.init.kaiming_normal(m.weight.data)
../models/posenet.py:64: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(m.bias.data, 0)
Loaded weights from logs/RobotCar_loop_mapnet++_mapnet++_RobotCar_learn_beta_learn_gamma_2seq/epoch_005.pth.tar
Running mapnet++ on VAL data
Traceback (most recent call last):
  File "eval.py", line 124, in <module>
    vo_func=vo_func, no_duplicates=False, **kwargs)
  File "../dataset_loaders/composite.py", line 51, in __init__
    self.dset = RobotCar(*args, real=self.real, **kwargs)
  File "../dataset_loaders/robotcar.py", line 50, in __init__
    with open(split_filename, 'r') as f:
IOError: [Errno 2] No such file or directory: '../data/deepslam_data/RobotCar/loop/test_split.txt'
```
where to download the file from? do I get it from http://robotcar-dataset.robots.ox.ac.uk/ ?
the text.split has been located at the current github repository, thank you.
Now it needs another file though:
`python eval.py --dataset RobotCar --scene loop --model mapnet++ --weights logs/RobotCar_loop_mapnet++_mapnet++_RobotCar_learn_beta_learn_gamma_2seq/epoch_005.pth.tar --config_file configs/pgo_inference_RobotCar.ini --val --pose_graph
../models/posenet.py:62: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  nn.init.kaiming_normal(m.weight.data)
../models/posenet.py:64: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(m.bias.data, 0)
Loaded weights from logs/RobotCar_loop_mapnet++_mapnet++_RobotCar_learn_beta_learn_gamma_2seq/epoch_005.pth.tar
Running mapnet++ on VAL data
Traceback (most recent call last):
  File "eval.py", line 124, in <module>
    vo_func=vo_func, no_duplicates=False, **kwargs)
  File "../dataset_loaders/composite.py", line 51, in __init__
    self.dset = RobotCar(*args, real=self.real, **kwargs)
  File "../dataset_loaders/robotcar.py", line 63, in __init__
    with open(ts_filename, 'r') as f:
IOError: [Errno 2] No such file or directory: '../data/deepslam_data/RobotCar/loop/2014-06-23-15-41-25/stereo.timestamps'`
I get the 1gb sample from oxford robotics, do I put it all just to /data/deepslam/RobotCar/ or I need to sort it out to different folders?
I copied the file manually to the error path but now it errors with vo.csv not presented.
Where to get normal structure of the folder 2014-06-23-15-41-25 ?
`cp stereo.timestamps /onepanel/code/data/deepslam_data/RobotCar/loop/2014-06-23-15-41-25/
(mapnet_release) /onepanel/code/data/deepslam_data/RobotCar/sample (master) $ cd ../
(mapnet_release) /onepanel/code/data/deepslam_data/RobotCar (master) $ cd ../../
(mapnet_release) /onepanel/code/data (master) $ cd ../scripts/
(mapnet_release) /onepanel/code/scripts (master) $ python eval.py --dataset RobotCar --scene loop --model mapnet++ --weights logs/RobotCar_loop_mapnet++_mapnet++_RobotCar_learn_beta_learn_gamma_2seq/epoch_005.pth.tar --config_file configs/pgo_inference_RobotCar.ini --val --pose_graph
../models/posenet.py:62: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  nn.init.kaiming_normal(m.weight.data)
../models/posenet.py:64: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(m.bias.data, 0)
Loaded weights from logs/RobotCar_loop_mapnet++_mapnet++_RobotCar_learn_beta_learn_gamma_2seq/epoch_005.pth.tar
Running mapnet++ on VAL data
Traceback (most recent call last):
  File "eval.py", line 124, in <module>
    vo_func=vo_func, no_duplicates=False, **kwargs)
  File "../dataset_loaders/composite.py", line 51, in __init__
    self.dset = RobotCar(*args, real=self.real, **kwargs)
  File "../dataset_loaders/robotcar.py", line 69, in __init__
    p = np.asarray(interpolate_vo_poses(vo_filename, ts[seq], ts[seq][0]))
  File "../dataset_loaders/robotcar_sdk/interpolate_poses.py", line 34, in interpolate_vo_poses
    with open(vo_path) as vo_file:
IOError: [Errno 2] No such file or directory: '../data/deepslam_data/RobotCar/loop/2014-06-23-15-41-25/vo/vo.csv'
(mapnet_release) /onepanel/code/scripts (master) $ cd ..`

**Comment by AndreV84** [comment]
if I am trying another sequence:
` python align_vo_poses.py --dataset 7Scenes --scene chess --seq 1 --vo_lib dso
Traceback (most recent call last):
  File "align_vo_poses.py", line 19, in <module>
    from dataset_loaders.robotcar_sdk.interpolate_poses import interpolate_ins_poses,\
ImportError: No module named robotcar_sdk.interpolate_poses`

**Comment by AndreV84** [comment]
python eval.py  --dataset 7Scenes --scene heads --model mapnet++ --weights logs/7Scenes_heads_mapnet++_mapnet++_7Scenes/epoch_005.pth.tar --config_file configs/pgo_inference_7Scenes.ini
../models/posenet.py:62: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  nn.init.kaiming_normal(m.weight.data)
../models/posenet.py:64: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(m.bias.data, 0)
Loaded weights from logs/7Scenes_heads_mapnet++_mapnet++_7Scenes/epoch_005.pth.tar
Running mapnet++ on TRAIN data
Traceback (most recent call last):
  File "eval.py", line 124, in <module>
    vo_func=vo_func, no_duplicates=False, **kwargs)
  File "../dataset_loaders/composite.py", line 45, in __init__
    self.dset = SevenScenes(*args, real=self.real, **kwargs)
  File "../dataset_loaders/seven_scenes.py", line 70, in __init__
    pss = np.loadtxt(pose_file)
  File "/home/onepanel/.conda/envs/mapnet_release/lib/python2.7/site-packages/numpy/lib/npyio.py", line 926, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/onepanel/.conda/envs/mapnet_release/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 260, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/onepanel/.conda/envs/mapnet_release/lib/python2.7/site-packages/numpy/lib/_datasource.py", line 616, in open
    raise IOError("%s not found." % path)
IOError: ../data/7Scenes/heads/orbslam_poses/seq-02.txt not found.

**Comment by samarth-robo** [comment]
Seems like you need to download the visual odometry file from the Oxford RobotCar website. See #11.

**Comment by AndreV84** [comment]
Thank you for letting me know!
