### ISSUE TITLE
Argument name seems wrong in process_robotcar_iamges.py

### ISSUE THREAD

**Issue by mrbulb** [NVlabs/geomapnet#7]
https://github.com/NVlabs/geomapnet/blob/e18b75684ae61ca502e7df0cb99edf45770ac57b/scripts/process_robotcar_images.py#L38

The argument here seems should be **scene=args.scene** rather than  **sequence=args.scene**, according to the `dataset_loaders/robotcar.py`
https://github.com/NVlabs/geomapnet/blob/e18b75684ae61ca502e7df0cb99edf45770ac57b/dataset_loaders/robotcar.py#L19

**Comment by AndreV84** [comment]
do you hve an idea from where to get  the vo.csv for the RobotCar?

**Comment by mr-bulb** [comment]
@AndreV84 I think you can download the `vo.csv` from the DataSet part of the [website](http://robotcar-dataset.robots.ox.ac.uk/datasets/2014-05-06-12-54-54/), just like following image:
![qq 20180829000718](https://user-images.githubusercontent.com/40812378/44735607-8942ea80-ab1f-11e8-9222-021bb19d5650.jpg)

**Comment by mrbulb** [comment]
@AndreV84 I think you can download the `vo.csv` from the DataSet part of the [website](http://robotcar-dataset.robots.ox.ac.uk/datasets/2014-05-06-12-54-54/), just like following image:
![qq 20180829000718](https://user-images.githubusercontent.com/40812378/44735607-8942ea80-ab1f-11e8-9222-021bb19d5650.jpg)

**Comment by AndreV84** [comment]
thank you

**Comment by AndreV84** [comment]
and gps? from where do I get the gps archive?
" No such file or directory: '../data/deepslam_data/RobotCar/loop/2014-06-23-15-41-25/gps/ins.csv"
thx

**Comment by mrbulb** [comment]
@AndreV84  in the same web page that I mention before

**Comment by AndreV84** [comment]
mrbulb, could you provide a hint what will be the name of the archive with gps at the [page](http://robotcar-dataset.robots.ox.ac.uk/datasets/2014-05-06-12-54-54/)
As I can see the below archives associated with the project:

2014-05-06-12-54-54_stereo_centre_01.tar | 2.83GB | EB4737F1133BD97CF1ED06BF0B7063BF
-- | -- | --
2014-05-06-12-54-54_stereo_left_01.tar | 2.77GB | DB26EB20BFB5A730DB191A4C69CD7733
2014-05-06-12-54-54_stereo_right_01.tar | 2.86GB | 03DE0241AED24B7DEB68F626CE52A5AF
2014-05-06-12-54-54_vo.tar | 440.00KB | 0F820A7C57B7CA0ACE2669E769AA8776

**Comment by AndreV84** [comment]
got it:

2014-05-06-12-54-54_gps.tar | 1.93MB | F8FFA266763BDA99CC68DA7CB9A2ECE2
-- | -- | --



thx

**Comment by AndreV84** [comment]
but now it says on me executing :
`python eval.py --dataset RobotCar --scene loop --model mapnet++ --weights logs/RobotCar_loop_mapnet++_mapnet++_RobotCar_learn_beta_learn_gamma_2seq/epoch_005.pth.tar --config_file configs/pgo_inference_RobotCar.ini --val --pose_graph`
`Could not load image ../data/deepslam_data/RobotCar/loop/2014-06-23-15-41-25/stereo/centre/1418381800826390.png, IOError: [Errno 2] No such file or directory: '../data/deepslam_data/RobotCar/loop/2014-06-23-15-41-25/stereo/centre/1418381800826390.png'
Could not load image ../data/deepslam_data/RobotCar/loop/2014-06-23-15-41-25/stereo/centre/1418381800888890.png, IOError: [Errno 2] No such file or directory: '../data/deepslam_data/RobotCar/loop/2014-06-23-15-41-25/stereo/centre/1418381800888890.png'`
the dataset I downloaded was http://mrgdatashare.robots.ox.ac.uk/download/?filename=datasets/2014-06-23-15-41-25/2014-06-23-15-41-25_stereo_centre_01.tar
and I just unpacked it to the loop folder of RobotCar folder.
Shall I download some other dataset?
currently the downloaded has different images numbers:
1403538187037944.png  1403538222975848.png  1403538259038757.png  1403538301914238.png  1403538338477142.png
1403538187100446.png  1403538223038352.png  1403538259101255.png  1403538301976739.png  1403538338539642.png

**Comment by AndreV84** [comment]
got it, it was wrong stereo.timestamps file, thx

**Comment by AndreV84** [comment]
![ma2vsfn](https://user-images.githubusercontent.com/16374873/44766632-dc319780-ab49-11e8-8f4c-c384e18cfd54.jpg)
seems working somehow, thanks

**Comment by samarth-robo** [comment]
@mrbulb: I fixed that issue, thanks for pointing it out!
