### ISSUE TITLE
Training Weight

### ISSUE THREAD

**Issue by drinkingcoder** [NVlabs/geomapnet#9]
Hello, I find beta and gamma are not valid in mapnet, and sax=0, srx=0, saq=-3, srq=-3 are used for absolute and relative pose loss, but  I can't get the precision that you state in the paper. Can you show the weight that you specified on sax,srx,saq,srq for robotcar-loop scene in mapnet?.

**Comment by samarth-robo** [comment]
Hi @drinkingcoder, thanks for raising this issue. We found that some small changes had crept in during the code release process, causing the training to not function properly. I fixed it in commit f7b912a5b1df3ea2196cb1f62b901dedd5828081. See also #10.
